staging:
  type: test
  script:
  - cp config.inc.php config.php 
  - php /home/gitlab/atoum.phar -d src/controllers/api/tests/units/
  only:
  - master

production:
  type: deploy
  script:
  - cp config.inc.php config.php 
  - php /home/gitlab/atoum.phar -d src/controllers/api/tests/units/
  only:
  - production